### ISSUE TITLE
not submitting on pressing enter key

### ISSUE THREAD

**Issue by ar-ray0111** [ElixirTechCommunity/ShakespearSpeak#1]
Instead of submitting on pressing enter the text is going to a new line

**Comment by praptisharma28** [comment]
please assign me this.

**Comment by AnushkaPhogat16** [comment]
Hey! I'd love to work on this issue. Pls consider assigning it to me. Thanks

**Comment by manisanghsharma** [comment]
#5 #5

**Comment by manisanghsharma** [comment]
#5
